json.id product.id
json.item_code product.item_code
json.item_name product.item_name
json.description product.description
json.price product.price
json.currency product.currency
json.stock_qty product.stock_qty
json.stock_status product.stock_status
json.item_group product.item_group
json.image_url product.image_url
json.variants product.variants
json.specs product.specs
json.formatted_text product.formatted_text
json.description_source product.description_source
json.erp_company product.erp_company
json.assistant_id product.assistant_id
json.account_id product.account_id
json.created_at product.created_at
json.updated_at product.updated_at
